In [1]:
from Prob_game.risky_bomb import *

In [42]:
class Sample_generation(object):
    
    """
    This is a docstring for the Prob_stats class.
    The aim of this class is to provide statistics and plots
    about the created probabiliteis within the Probs class.
    """
    
    def __init__(self,
                 count, 
                 probs,  
                 change_bomb  = "F", 
                 type_ = None,
                 n_play = 10,
                 **kwargs):
        
        self.count = count
        self.base = Risky_bomb(count = count,
                          probs = probs, 
                          a = kwargs.get('a'),
                          peak = kwargs.get('peak'),
                          smooth = kwargs.get('smooth'),
                          n =  kwargs.get('n'),
                          po =  kwargs.get('po'),
                          df =  kwargs.get('df'))
        
        self.p = self.base.p
        self.cp = np.cumsum(self.p)
        self.change_bomb = change_bomb
        if n_play < 1:
            raise ValueError("Parameter n_play must be at least 1")
        self.n_play = n_play
        self.w_input = None
        self.w_output = None
        
        self.gen_sample_df = pd.DataFrame()
    
    def gen_sample(self, flag = 1, n_sample = 5):
        
        df_out = pd.DataFrame(columns = ["Sample_ID",
                                         "seq", 
                                         "flag",
                                         "payment",
                                         "guesses",
                                         "bomb",
                                         "mean_guess",
                                         "std_guess",
                                         "mean_p",
                                         "std_p",
                                         "last_3_p_mean"])
        for j in range(0, n_sample - 1):
            
             # Initiate values
            seq_ = []
            flag_ = []
            guess_in = []
            p = []
            bomb = []
            mean_guess = []
            std_guess = []
            mean_p = []
            std_p = []
            last_3_p_mean= []

            for i in range(0, self.n_play):  
                seq_.append(i)
                flag_.append(flag)
                guess_in.append(np.random.randint(0,self.count))
                p.append(self.base.payment(guess = guess_in[i], change_bomb = self.change_bomb))
                bomb.append(self.base.bomb)
                mean_guess.append(np.mean(guess_in))
                std_guess.append(np.std(guess_in))
                mean_p.append(np.mean(p))
                std_p.append(np.std(p))
                if len(p) < 3:
                    c = 0
                else: 
                    c = len(p) - 3
                last_3_p_mean.append(np.mean(p[c:]))
                
            out_ = pd.DataFrame({"Sample_ID": j,
                                 "seq": seq_,
                                 "flag": flag_,
                                 "payment": p,
                                 "guesses": guess_in, 
                                 "bomb":bomb,
                                 "mean_guess": mean_guess, 
                                 "std_guess": std_guess,
                                 "mean_p": mean_p, 
                                 "std_p": std_p,
                                 "last_3_p_mean": last_3_p_mean})
            
            df_out = df_out.append(out_ , ignore_index = True)
        
        self.gen_sample_df = df_out
        return(df_out)

In [43]:
a = Sample_generation(count = 99, probs = "skewnorm", a = 10, change_bomb = "T", n_play = 50 )

In [44]:
a.gen_sample()

,Sample_ID,seq,flag,payment,guesses,bomb,mean_guess,std_guess,mean_p,std_p,last_3_p_mean
0,0,0,1,31,31,43,31.000000,0.000000,31.000000,0.000000,31.000000
1,0,1,1,0,46,40,38.500000,7.500000,15.500000,15.500000,15.500000
2,0,2,1,0,80,25,52.333333,20.499322,10.333333,14.613540,10.333333
3,0,3,1,18,18,24,43.750000,23.155723,12.250000,13.083864,6.000000
4,0,4,1,0,36,29,42.200000,20.941824,9.800000,12.687001,6.000000
5,0,5,1,0,46,25,42.833333,19.169565,8.166667,12.143814,6.000000
6,0,6,1,0,44,33,43.000000,17.752263,7.000000,11.600493,0.000000
7,0,7,1,0,81,41,47.750000,20.825165,6.125000,11.095466,0.000000
8,0,8,1,6,6,21,43.111111,23.614706,6.111111,10.460980,2.000000
9,0,9,1,0,68,38,45.600000,23.614402,5.500000,10.092076,2.000000
10,0,10,1,0,76,31,48.363636,24.152066,5.000000,9.751457,2.000000
11,0,11,1,0,73,29,50.416667,24.105526,4.583333,9.438029,0.000000
12,0,12,1,35,35,36,49.230769,23.521361,6.923077,12.162120,11.666667
13,0,13,1,0,85,30,51.785714,24.466241,6.428571,11.854561,11.666667
14,0,14,1,0,80,30,53.666667,24.662162,6.000000,11.564313,11.666667
15,0,15,1,23,23,41,51.750000,25.006249,7.062500,11.929317,7.666667
16,0,16,1,0,41,16,51.117647,24.391132,6.647059,11.691833,7.666667
17,0,17,1,3,3,29,48.444444,26.141118,6.444444,11.393089,8.666667
18,0,18,1,0,51,17,48.578947,25.450294,6.105263,11.182198,1.000000
19,0,19,1,31,31,42,47.700000,25.100000,7.350000,12.174872,11.333333
20,0,20,1,0,51,31,47.857143,24.505171,7.000000,11.984116,10.333333
21,0,21,1,0,56,21,48.227273,24.001765,6.681818,11.799023,10.333333
22,0,22,1,0,55,17,48.521739,23.514786,6.391304,11.619845,0.000000
23,0,23,1,0,31,25,47.791667,23.284435,6.125000,11.446661,0.000000
24,0,24,1,0,43,19,47.600000,22.833309,5.880000,11.279433,0.000000
25,0,25,1,0,44,17,47.461538,22.400602,5.653846,11.118046,0.000000
26,0,26,1,0,28,10,46.740741,22.287004,5.444444,10.962337,0.000000
27,0,27,1,0,74,34,47.714286,22.462440,5.250000,10.812113,0.000000
28,0,28,1,0,68,14,48.413793,22.379974,5.068966,10.667162,0.000000
29,0,29,1,0,63,34,48.900000,22.159046,4.900000,10.527266,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
170,3,20,1,0,25,6,51.428571,31.313425,2.571429,7.095078,0.000000
171,3,21,1,0,33,17,50.590909,30.833363,2.454545,6.952614,0.000000
172,3,22,1,5,5,9,48.608696,31.556353,2.565217,6.819576,1.666667
173,3,23,1,0,82,51,50.000000,31.604325,2.458333,6.695640,1.666667
174,3,24,1,39,39,43,49.560000,31.040722,3.920000,9.711519,14.666667
175,3,25,1,4,4,11,47.807692,31.673842,3.923077,9.522940,14.333333
176,3,26,1,0,45,23,47.703704,31.086278,3.777778,9.374249,14.333333
177,3,27,1,0,65,24,48.321429,30.694408,3.642857,9.231987,1.333333
178,3,28,1,0,84,17,49.551724,30.855152,3.517241,9.095739,0.000000
179,3,29,1,0,71,43,50.266667,30.579877,3.400000,8.965118,0.000000
180,3,30,1,24,24,37,49.419355,30.438488,4.064516,9.540865,8.000000
181,3,31,1,0,76,29,50.250000,30.313982,3.937500,9.417197,8.000000
182,3,32,1,0,29,29,49.606061,30.072578,3.818182,9.297946,8.000000
183,3,33,1,0,78,18,50.441176,30.012930,3.705882,9.182879,0.000000
184,3,34,1,0,92,10,51.628571,30.380525,3.600000,9.071777,0.000000
185,3,35,1,0,96,14,52.861111,30.830318,3.500000,8.964436,0.000000
186,3,36,1,16,16,30,51.864865,30.992730,3.837838,9.071826,5.333333
187,3,37,1,0,32,26,51.342105,30.747081,3.736842,8.972720,5.333333
188,3,38,1,0,91,42,52.358974,30.990890,3.641026,8.876611,5.333333
189,3,39,1,0,98,11,53.500000,31.419739,3.550000,8.783365,0.000000
190,3,40,1,0,54,18,53.512195,31.034302,3.463415,8.692855,0.000000
191,3,41,1,0,47,43,53.357143,30.678689,3.380952,8.604961,0.000000
192,3,42,1,0,91,59,54.232558,30.846082,3.302326,8.519567,0.000000
193,3,43,1,0,88,45,55.000000,30.906016,3.227273,8.436564,0.000000
194,3,44,1,0,79,32,55.533333,30.764771,3.155556,8.355851,0.000000
195,3,45,1,0,84,44,56.152174,30.710406,3.086957,8.277329,0.000000
196,3,46,1,0,75,22,56.553191,30.503441,3.021277,8.200906,0.000000
197,3,47,1,0,94,56,57.333333,30.654209,2.958333,8.126496,0.000000
198,3,48,1,29,29,35,56.755102,30.603142,3.489796,8.845897,9.666667
199,3,49,1,0,42,35,56.460000,30.365909,3.420000,8.770610,9.666667

In [53]:
# Number of samples by Prob. dist.
n_sample_ = 600

# Skewnorm
skewnorm = Sample_generation(count = 99, probs = "skewnorm", a = 10, change_bomb = "T", n_play = 50 )
sknewnorm_df = skewnorm.gen_sample(flag = 1, n_sample = n_sample_)

# Random Skew
random_skew = Sample_generation(count= 99, probs = "random_skew", peak = 80, smooth = "True", change_bomb = "T", n_play = 50 )
random_skew_df = random_skew.gen_sample(flag = 2, n_sample = n_sample_)

# Increasing
increasing = Sample_generation(count= 99, probs = "increasing", change_bomb = "T", n_play = 50 )
increasing_df = increasing.gen_sample(flag = 3, n_sample = n_sample_)

final_df = pd.DataFrame()

final_df = final_df.append(sknewnorm_df, ignore_index = True)
final_df = final_df.append(random_skew_df, ignore_index = True)
final_df = final_df.append(increasing_df, ignore_index = True)

In [51]:
final_df.head()

,Sample_ID,seq,flag,payment,guesses,bomb,mean_guess,std_guess,mean_p,std_p,last_3_p_mean
0,0,0,1,0,67,53,67.000000,0.000000,0.0,0.0,0.0
1,0,1,1,0,75,9,71.000000,4.000000,0.0,0.0,0.0
2,0,2,1,0,55,50,65.666667,8.219219,0.0,0.0,0.0
3,0,3,1,0,65,16,65.500000,7.123903,0.0,0.0,0.0
4,0,4,1,0,41,23,60.600000,11.689311,0.0,0.0,0.0

In [54]:
final_df.to_csv("training_sample.csv", index = False)